export const FEEDBACK_ROUTE = '/feedback'
export const LIST_MENU_ROUTE = '/menu/:idUser'
export const BASKET_USER_ROUTE = '/basket/:idUser'
export const PRODUCT_CARD_ROUTE = '/cardProduct/:idUser/:idProduct'
export const MENU_PROMO_CODE_ROUTE = '/promocode/:idUser'
export const PERSONAL_DATA = '/personalData/:idUser'
export const PERSONAL_ORDERS = '/personalOrders/:idUser'